name="situation"
for i in name:
    print(i)
    for i in name:
          print(i)


name="sharukh khan"

for words in name:
     print(words,"line 1")



# Range istemal hota hai numbers print krne ke liye ke yhn se lekr yhn tk mujhe numbe chaiyen
""" it takes three paramter

1. kahan se start krna 
2. kahan tak end krna hai ye usmain se ek minus krke deta hai
3. kitne step chalana hai matlab agr ap step deta ho jese 2 to ye two plus krke answer karega aur two jo hai one main plus krega

"""
for i in range(1,10,2):
     print(i)


array=["apple","mango","orange","peach"]


for color in array:
 print(color)
 for by in array:
    print(by)
      

